#!/usr/bin/env bash
# =====================================================================
# Stage 3: SROS2 keystore bootstrap.
#
# Creates the X.509 PKI used by the safety supervisor and its peers.
# Idempotent: if the keystore already exists with all enclaves we do
# nothing; otherwise the missing pieces are created.
#
# Layout under ${KEYSTORE_DIR}:
#   public/                              CA cert + identity store
#   private/                             CA private key (root of trust)
#   enclaves/
#     /lab/safety_supervisor/            owner of /safety/state, /safety/request
#     /lab/production_plc/               heartbeat publisher
#     /lab/ai_subscriber/                read-only subscriber to /safety/state
#     /lab/cyclic_motion/                Gazebo motion node, subscribes /safety/state
#     /lab/test_unauthorized/            INTENTIONALLY ABSENT — used to verify
#                                        that an unsigned client is rejected
#                                        (created on demand by the test, see
#                                        infra/tests/stage3_sros2_authn.py).
#
# Permissions are templated under: ${TEMPLATE_DIR}/permissions/<enclave>.xml
# =====================================================================
# NOTE: ROS Humble's setup.bash uses `$AMENT_TRACE_SETUP_FILES` without
# initializing it, which trips `set -u`. We disable `-u` while sourcing
# ROS and restore it afterwards.
set -eo pipefail

KEYSTORE_DIR="${LAB_SROS2_KEYSTORE:-/opt/lab/sros2_keystore}"
TEMPLATE_DIR="${LAB_SROS2_TEMPLATE_DIR:-/vagrant/vm-ot/sros2/permissions}"
ROS_SETUP="${ROS_SETUP:-/opt/ros/humble/setup.bash}"

log() { printf '[sros2-bootstrap] %s\n' "$*"; }

if [[ ! -f "${ROS_SETUP}" ]]; then
    echo "[sros2-bootstrap] FATAL: ${ROS_SETUP} not found; ROS2 Humble must be installed first" >&2
    exit 1
fi

# Source ROS so `ros2 security` is on PATH.
# shellcheck disable=SC1090
set +u
source "${ROS_SETUP}"
set -u

ENCLAVES=(
    "/lab/safety_supervisor"
    "/lab/production_plc"
    "/lab/ai_subscriber"
    "/lab/cyclic_motion"
)

# 1. Keystore root.
if [[ ! -d "${KEYSTORE_DIR}/public" ]]; then
    log "creating keystore at ${KEYSTORE_DIR}"
    install -d -m 0755 "${KEYSTORE_DIR}"
    ros2 security create_keystore "${KEYSTORE_DIR}"
else
    log "keystore already exists at ${KEYSTORE_DIR}"
fi

# 2. Per-enclave identity + permissions.
for enclave in "${ENCLAVES[@]}"; do
    enclave_path="${KEYSTORE_DIR}/enclaves${enclave}"
    if [[ ! -f "${enclave_path}/cert.pem" ]]; then
        log "creating enclave ${enclave}"
        ros2 security create_enclave "${KEYSTORE_DIR}" "${enclave}"
    else
        log "enclave ${enclave} already present"
    fi

    # DESIGN NOTE — topic-level ACLs:
    #
    # We previously overwrote the default permissions.p7s generated by
    # `ros2 security create_enclave` with explicit per-topic allow rules
    # signed by the Permissions CA. The XML+signature were syntactically
    # valid (verified by `openssl smime -verify`), but Cyclone DDS in
    # ROS Humble silently hung at participant creation when they were
    # active — both the supervisor and clients failed to complete DDS
    # discovery. Reverting to the default (wide-open within the keystore)
    # permissions makes discovery and publish work normally.
    #
    # AUDIT IMPLICATIONS:
    #   - The PKI authentication boundary (Stage 3 GATE 2 / unsigned-client
    #     rejection) is *unaffected*: DDS-Security still requires every
    #     participant to present a Permissions-CA-signed cert chain. An
    #     attacker without an enclave cannot speak the protocol at all.
    #   - Topic-level read/write ACLs (e.g. ai_subscriber MUST NOT publish
    #     rt/safety/request even though it owns a valid cert) are NOT
    #     enforced by DDS in this configuration. They are documented as
    #     future work — see STAGE3_CHECKLIST.md.
    #
    # The template files under permissions/*.permissions.xml are kept in
    # the repo as the *intended* ACL document; they are not installed
    # into the live keystore today.
    # SROS2 custom permissions signing block is disabled to use default working enclaves,
    # avoiding Cyclone DDS discovery issues as noted in the design note.
    # template="${TEMPLATE_DIR}/$(basename "${enclave}").permissions.xml"
    # target_xml="${enclave_path}/permissions.xml"
    # if [[ -f "${template}" ]]; then
    #     log "installing and signing custom permissions for ${enclave}"
    #     install -m 0644 "${template}" "${target_xml}"
    #     # Sign the custom permissions XML to produce permissions.p7s
    #     ros2 security create_permission "${KEYSTORE_DIR}" "${enclave}" "${target_xml}"
    # fi
done

log "keystore ready: ${KEYSTORE_DIR}"
log "enclaves: ${ENCLAVES[*]}"
